# Minimal Alacritty configuration for debugging
# ~/.config/alacritty/alacritty.toml

[terminal.shell]
program = "/bin/zsh"

[font]
normal = { family = "monospace" }
size = 11.0

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

[window]
opacity = 1.0
decorations = "full"

[env]
TERM = "xterm-256color"
